category: Network
description: Wuss is a library that lets you easily create secure WebSocket
  clients over the WSS protocol. It is a small addition to
  <https://hackage.haskell.org/package/websockets the websockets package> and
  is adapted from existing solutions by
  <https://gist.github.com/jaspervdj/7198388 @jaspervdj>,
  <https://gist.github.com/mpickering/f1b7ba3190a4bb5884f3 @mpickering>, and
  <https://gist.github.com/elfenlaid/7b5c28065e67e4cf0767 @elfenlaid>.
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- stack.yaml
ghc-options: -Wall
github: tfausak/wuss
library:
  dependencies:
  - base ==4.*
  - bytestring
  - connection ==0.2.*
  - network
  - websockets ==0.9.*
  exposed-modules: Wuss
license: MIT
maintainer: Taylor Fausak
name: wuss
synopsis: Secure WebSocket (WSS) clients
version: '1.1.0'
